name: Apple Silicon

on: 
  push:
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        type: [Debug, Release]
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          brew update
          brew install llvm@19
      - name: Clone GTest
        run: git clone https://github.com/google/googletest.git
      - name: Build and run
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -DCT_LLVM_INSTALL_DIR="/opt/homebrew/opt/llvm@19/" -DCMAKE_BUILD_TYPE=${{ matrix.type }}  ../
          make -j8
          ./cppTutorUT
